// 2026년 기본서식. 이미 이 버전으로 저장된 기록이 있으므로 내용을 바꾸지 마세요.
// 서식이 개정되면 이 파일을 복사해 새 버전 파일을 만들고 registry에 등록합니다.
// responses(JSONB)의 각 값은 field.code를 key로 저장됩니다.

import type { Section } from "./types";

const SCALE4_OPTIONS = [
  "0 · 혼자 할 수 있음",
  "1 · 지시(준비)도움",
  "2 · 직접(부축)도움",
  "3 · 전혀 수행할 수 없음",
];

const COMM_SCALE_OPTIONS = ["양호", "약간 어려움", "단순 소통만 가능", "이해/표현하지 못함", "측정불가"];

export const V2026_SECTIONS: Section[] = [
  {
    code: "s1",
    title: "1. 일반사항",
    fields: [
      { code: "s1_position", label: "작성자 직종", type: "text", group: "작성 정보" },
      {
        code: "s1_type",
        label: "욕구조사 유형",
        type: "select",
        options: ["최초", "정기", "상태변화", "기타"],
      },
      { code: "s1_type_etc", label: "유형 기타 사유", type: "text" },
      {
        code: "s1_interviewee",
        label: "면담자",
        type: "select",
        options: ["수급자", "보호자"],
        group: "면담자",
      },
      { code: "s1_interviewee_name", label: "보호자 성명 (면담자가 보호자인 경우)", type: "text" },
      {
        code: "s1_primary_caregiver_present",
        label: "주 수발자 여부",
        type: "select",
        options: ["Y", "N"],
      },
    ],
  },
  {
    code: "s2",
    title: "2. 일반적 건강상태",
    fields: [
      { code: "s2_height", label: "키", type: "number", suffix: "cm", group: "신체계측" },
      { code: "s2_weight", label: "체중", type: "number", suffix: "kg" },
      {
        code: "s2a_diseases",
        label: "보유질환",
        type: "multiselect",
        group: "가. 보유질환",
        options: [
          "없음",
          "뇌졸중(뇌출혈,뇌경색증)",
          "치매",
          "파킨슨병",
          "우울증",
          "고혈압",
          "협심증",
          "심근경색증",
          "천식",
          "만성폐쇄성폐질환",
          "당뇨",
          "고지혈증",
          "관절염(퇴행성·류마티스)",
          "골다공증",
          "골절·탈골 등 사고로 인한 후유증",
          "만성신부전",
          "요로감염",
          "만성방광염",
          "전립선비대",
          "백내장",
          "녹내장",
          "난청",
          "만성중이염",
          "이명",
          "결핵",
          "옴",
          "다약제내성균",
          "암",
          "알레르기",
        ],
        // 원본 서식은 질환을 계통별로 줄을 나눠 배치합니다.
        optionGroups: [
          { label: "", options: ["없음"] },
          { label: "뇌신경계", options: ["뇌졸중(뇌출혈,뇌경색증)", "치매", "파킨슨병", "우울증"] },
          {
            label: "호흡·순환기계",
            options: ["고혈압", "협심증", "심근경색증", "천식", "만성폐쇄성폐질환"],
          },
          { label: "내분비·대사", options: ["당뇨", "고지혈증"] },
          {
            label: "근골격계",
            options: ["관절염(퇴행성·류마티스)", "골다공증", "골절·탈골 등 사고로 인한 후유증"],
          },
          {
            label: "비뇨생식기계",
            options: ["만성신부전", "요로감염", "만성방광염", "전립선비대"],
          },
          { label: "감각계", options: ["백내장", "녹내장", "난청", "만성중이염", "이명"] },
          { label: "감염", options: ["결핵", "옴", "다약제내성균"] },
          { label: "기타 질환", options: ["암", "알레르기"] },
        ],
      },
      { code: "s2a_cancer_name", label: "암 진단명", type: "text" },
      { code: "s2a_allergy_detail", label: "알레르기 상세 (식품·약물·접촉성 등)", type: "text" },
      { code: "s2a_amr_type", label: "다약제내성균 종류", type: "text" },
      { code: "s2a_etc", label: "기타 질환", type: "text" },
      {
        code: "s2b_medication",
        label: "복약 및 의료이용",
        type: "multiselect",
        group: "나. 복약 및 의료이용",
        options: [
          "복용하는 약이 없음",
          "정기적 약 복용",
          "비정기적 약 복용",
          "수면장애로 인한 약 복용",
          "기타",
        ],
      },
      { code: "s2b_regular_reason", label: "정기적 약 복용 사유", type: "text" },
      { code: "s2b_hospital", label: "병원명", type: "text" },
      { code: "s2b_visit_cycle", label: "진료주기 (월 몇 회)", type: "text" },
      { code: "s2b_irregular_reason", label: "비정기적 약 복용 사유", type: "text" },
      { code: "s2b_etc", label: "복약 기타", type: "text" },
      {
        code: "s2c_oral_state",
        label: "구강상태",
        type: "select",
        group: "다. 구강과 영양상태",
        options: ["양호", "틀니착용(부분)", "틀니착용(완전)", "잔존치아없음", "기타"],
      },
      { code: "s2c_oral_state_etc", label: "구강상태 기타", type: "text" },
      {
        code: "s2c_oral_health",
        label: "구강건강",
        type: "select",
        options: ["양호", "구취/위생불량", "잇몸출혈/통증", "구강건조", "기타"],
      },
      { code: "s2c_oral_health_etc", label: "구강건강 기타", type: "text" },
      {
        code: "s2c_meal_form",
        label: "식사형태",
        type: "select",
        options: ["일반식", "다진식", "죽", "유동식", "경관영양", "기타"],
      },
      { code: "s2c_meal_form_etc", label: "식사형태 기타", type: "text" },
      {
        code: "s2c_therapeutic_diet",
        label: "치료식",
        type: "select",
        options: ["해당없음", "당뇨식", "저염식", "기타"],
      },
      { code: "s2c_therapeutic_diet_etc", label: "치료식 기타", type: "text" },
      {
        code: "s2c_meal_notes",
        label: "식사제공 유의사항",
        type: "textarea",
        // 공단 평가 세부내용 5번의 '기피식품 파악'을 이 칸에서 확인합니다(2026.1월~).
        placeholder:
          "기피식품(종교·알러지·소화·기호 등으로 못 드시는 식품), 식사형태와 패턴, 연하곤란 등을 구체적으로 작성",
      },
      { code: "s2c_nutrition", label: "영양상태", type: "select", options: ["양호", "불량"] },
      {
        code: "s2c_nutrition_detail",
        label: "영양상태 불량 상세",
        type: "multiselect",
        options: ["식욕부진", "체중감소", "체중과다", "기타"],
      },
      { code: "s2_opinion", label: "의견 및 판단근거", type: "textarea", group: "라. 의견" },
    ],
  },
  {
    code: "s3",
    title: "3. 일상생활기능",
    note: "0 혼자 할 수 있음, 1 지시(준비)도움, 2 직접(부축)도움, 3 전혀 수행할 수 없음",
    fields: [
      { code: "s3_wash_face", label: "세수하기", type: "scale4", options: SCALE4_OPTIONS, group: "가. 위생관리" },
      { code: "s3_brush_teeth", label: "양치질하기(틀니관리)", type: "scale4", options: SCALE4_OPTIONS },
      { code: "s3_toilet_use", label: "화장실(이동변기) 사용하기", type: "scale4", options: SCALE4_OPTIONS },
      { code: "s3_body_wash", label: "몸 씻기", type: "scale4", options: SCALE4_OPTIONS },
      { code: "s3_dressing", label: "옷 벗고 입기", type: "scale4", options: SCALE4_OPTIONS, group: "나. 일상생활" },
      { code: "s3_eating", label: "식사하기", type: "scale4", options: SCALE4_OPTIONS },
      { code: "s3_swallowing", label: "음식 삼키기", type: "scale4", options: SCALE4_OPTIONS },
      { code: "s3_cleaning", label: "청소 및 정리정돈", type: "scale4", options: SCALE4_OPTIONS, group: "다. 도구적 일상생활" },
      { code: "s3_meal_prep", label: "식사 준비하기", type: "scale4", options: SCALE4_OPTIONS },
      { code: "s3_laundry", label: "빨래하기", type: "scale4", options: SCALE4_OPTIONS },
      { code: "s3_transport", label: "교통수단 이용하기", type: "scale4", options: SCALE4_OPTIONS },
      { code: "s3_medication", label: "약 챙겨먹기", type: "scale4", options: SCALE4_OPTIONS },
      { code: "s3_shopping", label: "물건사기", type: "scale4", options: SCALE4_OPTIONS },
      {
        code: "s3_urination_function",
        label: "배뇨기능",
        type: "select",
        group: "라. 배뇨기능 및 방법",
        options: ["양호", "요실금", "배뇨곤란(배뇨 시 통증, 배뇨지연 등)", "요의 느끼지 못함", "기타"],
      },
      { code: "s3_urination_function_etc", label: "배뇨기능 기타", type: "text" },
      {
        code: "s3_urination_method",
        label: "배뇨방법",
        type: "select",
        options: ["화장실", "이동변기", "기저귀", "배뇨관(유치도뇨관·방광루 등)", "기타"],
      },
      { code: "s3_urination_method_etc", label: "배뇨방법 기타", type: "text" },
      {
        code: "s3_defecation_function",
        label: "배변기능",
        type: "select",
        group: "마. 배변기능 및 방법",
        options: ["양호", "변실금", "잦은 설사", "변비", "변의 느끼지 못함", "기타"],
      },
      { code: "s3_defecation_function_etc", label: "배변기능 기타", type: "text" },
      {
        code: "s3_defecation_method",
        label: "배변방법",
        type: "select",
        options: ["화장실", "이동변기", "기저귀", "장루", "기타"],
      },
      { code: "s3_defecation_method_etc", label: "배변방법 기타", type: "text" },
      { code: "s3_opinion", label: "의견 및 판단근거", type: "textarea", group: "바. 의견" },
    ],
  },
  {
    code: "s4",
    title: "4. 재활 및 신체기능",
    fields: [
      {
        code: "s4_contracture",
        label: "관절구축",
        type: "multiselect",
        group: "가. 근골격계 증상",
        options: ["없음", "상지 좌", "상지 우", "하지 좌", "하지 우"],
      },
      { code: "s4_contracture_site", label: "관절구축 부위 상세", type: "text" },
      {
        code: "s4_motor_impair",
        label: "운동장애",
        type: "multiselect",
        options: ["없음", "상지 좌", "상지 우", "하지 좌", "하지 우"],
      },
      { code: "s4_motor_impair_site", label: "운동장애 부위 상세", type: "text" },
      {
        code: "s4_paralysis",
        label: "마비",
        type: "multiselect",
        options: ["없음", "상지 좌", "상지 우", "하지 좌", "하지 우"],
      },
      { code: "s4_paralysis_site", label: "마비 부위 상세", type: "text" },
      {
        code: "s4_amputation",
        label: "절단",
        type: "multiselect",
        options: ["없음", "상지 좌", "상지 우", "하지 좌", "하지 우"],
      },
      { code: "s4_amputation_site", label: "절단 부위 상세", type: "text" },
      {
        code: "s4_gait",
        label: "보행상태",
        type: "select",
        group: "나. 보행상태",
        options: [
          "자립보행 가능",
          "보장구를 사용하여 자립보행 가능",
          "부축해주면 보행 가능",
          "보장구를 사용하여 부축을 받아 보행 가능",
          "보행 불가",
        ],
      },
      {
        code: "s4_gait_aid",
        label: "보장구 종류",
        type: "multiselect",
        options: ["지팡이", "성인용 보행기", "휠체어", "기타"],
      },
      { code: "s4_gait_aid_etc", label: "보장구 기타", type: "text" },
      {
        code: "s4_fall",
        label: "지난 3개월간 낙상",
        type: "select",
        group: "다. 낙상",
        options: ["없음", "있음"],
      },
      { code: "s4_fall_count", label: "낙상 횟수", type: "number" },
      { code: "s4_roll_over", label: "누운 상태에서 옆으로 돌아눕기", type: "scale4", options: SCALE4_OPTIONS, group: "라. 신체기능" },
      { code: "s4_sit_up", label: "누운 상태에서 몸 일으켜 앉기", type: "scale4", options: SCALE4_OPTIONS },
      { code: "s4_stand_up", label: "바닥에 앉은 상태에서 일어서기", type: "scale4", options: SCALE4_OPTIONS },
      { code: "s4_indoor_walk", label: "실내 보행하기", type: "scale4", options: SCALE4_OPTIONS },
      { code: "s4_opinion", label: "의견 및 판단근거", type: "textarea", group: "마. 의견" },
    ],
  },
  {
    code: "s5",
    title: "5. 간호관리",
    fields: [
      {
        code: "s5_respiratory",
        label: "호흡기간호",
        type: "multiselect",
        group: "가. 호흡기간호",
        options: ["없음", "기관절개관", "흡인", "산소요법", "분무요법(네뷸라이저)", "기타"],
      },
      { code: "s5_respiratory_etc", label: "호흡기간호 기타", type: "text" },
      {
        code: "s5_skin",
        label: "피부간호",
        type: "multiselect",
        group: "나. 피부간호",
        options: ["없음", "욕창", "말초신경병증궤양(당뇨발 등)", "화상", "소양증", "기타"],
      },
      { code: "s5_bedsore_site", label: "욕창 부위", type: "text" },
      {
        code: "s5_bedsore_stage",
        label: "욕창 단계",
        type: "select",
        options: ["1단계", "2단계", "3단계", "4단계"],
      },
      { code: "s5_skin_etc", label: "피부간호 기타", type: "text" },
      {
        code: "s5_digestive",
        label: "소화기간호",
        type: "multiselect",
        group: "다. 소화기간호",
        options: ["없음", "비위관", "위관", "기타"],
      },
      { code: "s5_digestive_etc", label: "소화기간호 기타", type: "text" },
      {
        code: "s5_pain_type",
        label: "통증 유형",
        type: "select",
        group: "라. 통증간호",
        options: ["없음", "일반통증", "암성통증"],
      },
      { code: "s5_pain_site", label: "통증 부위", type: "text" },
      { code: "s5_pain_level", label: "통증 정도 (0=전혀없음 ~ 10=매우심함)", type: "number" },
      {
        code: "s5_pain_frequency",
        label: "통증빈도",
        type: "select",
        options: ["일 1회 이상", "주 1회 이상"],
      },
      {
        code: "s5_pain_management",
        label: "통증관리",
        type: "multiselect",
        options: ["일반진통제", "마약성 진통제 패치", "마약성 경구 진통제", "냉·온요법", "마약성 주사제", "기타"],
      },
      { code: "s5_pain_management_etc", label: "통증관리 기타", type: "text" },
      {
        code: "s5_urinary",
        label: "배뇨간호",
        type: "multiselect",
        group: "마. 배뇨간호",
        options: ["없음", "유치도뇨관", "단순도뇨", "요루", "방광루", "투석", "기타"],
      },
      { code: "s5_dialysis_type", label: "투석 유형", type: "select", options: ["혈액", "복막"] },
      { code: "s5_urinary_etc", label: "배뇨간호 기타", type: "text" },
      {
        code: "s5_defecation",
        label: "배변간호",
        type: "multiselect",
        group: "바. 배변간호",
        options: ["없음", "장루", "관장", "기타"],
      },
      { code: "s5_defecation_etc", label: "배변간호 기타", type: "text" },
      {
        code: "s5_endocrine",
        label: "내분비간호",
        type: "multiselect",
        group: "사. 내분비간호",
        options: ["없음", "인슐린투여", "기타"],
      },
      { code: "s5_endocrine_etc", label: "내분비간호 기타", type: "text" },
      { code: "s5_opinion", label: "의견 및 판단근거", type: "textarea", group: "아. 의견" },
    ],
  },
  {
    code: "s6",
    title: "6. 인지 및 의사소통",
    note: "해당되는 증상에 모두 표기",
    fields: [
      {
        code: "s6_cognition",
        label: "인지기능",
        type: "multiselect",
        group: "가. 인지기능",
        options: [
          "양호",
          "기억력저하(단기)",
          "기억력저하(장기)",
          "지남력저하(시간)",
          "지남력저하(장소)",
          "지남력저하(사람)",
          "판단력저하",
          "이해력저하",
          "주의력저하",
        ],
      },
      {
        code: "s6_behavior",
        label: "행동증상",
        type: "multiselect",
        group: "나. 행동증상",
        options: [
          "없음",
          "망상",
          "환각(환청·환시 등)",
          "길잃음",
          "도움에저항",
          "불규칙수면",
          "배회",
          "공격성(언어적)",
          "공격성(비언어적)",
          "부적절한 행동",
          "불결행동",
          "식습관 변화(식사거부, 과다 등)",
          "부적절한 옷 입기",
          "반복적인 말이나 행동",
        ],
      },
      {
        code: "s6_psychology",
        label: "심리증상",
        type: "multiselect",
        group: "다. 심리증상",
        options: ["없음", "우울감", "무기력·무감동", "불안·초조", "기타"],
      },
      { code: "s6_psychology_etc", label: "심리증상 기타", type: "text" },
      {
        code: "s6_comprehension",
        label: "이해능력",
        type: "select",
        group: "라. 의사소통",
        options: COMM_SCALE_OPTIONS,
      },
      { code: "s6_expression", label: "표현능력", type: "select", options: COMM_SCALE_OPTIONS },
      {
        code: "s6_vision",
        label: "시력상태",
        type: "select",
        options: ["정상", "1미터 거리 보임", "근접한 사물 보임", "보이지 않음", "판단불능"],
      },
      { code: "s6_vision_glasses", label: "안경 사용", type: "select", options: ["예", "아니오"] },
      {
        code: "s6_hearing",
        label: "청력상태",
        type: "select",
        options: ["정상", "먼 곳의 소리는 들리지 않음", "큰 소리만 들림", "들리지 않음", "판단불능"],
      },
      { code: "s6_hearing_aid", label: "보청기 사용", type: "select", options: ["예", "아니오"] },
      { code: "s6_opinion", label: "의견 및 판단근거", type: "textarea", group: "마. 의견" },
    ],
  },
  {
    code: "s7",
    title: "7. 수급자의 가족 및 지지체계",
    fields: [
      {
        code: "s7_housing_type",
        label: "수급자의 주거형태",
        type: "select",
        group: "가. 주거상태",
        options: ["자택", "노인요양시설(노인요양공동생활가정 포함)", "양로시설", "요양병원", "기타"],
      },
      { code: "s7_housing_type_etc", label: "주거형태 기타", type: "text" },
      {
        code: "s7_cohabitant",
        label: "동거인",
        type: "multiselect",
        options: ["독거", "배우자", "자녀", "며느리·사위", "형제·자매", "손자녀", "부모", "친척", "기타"],
      },
      { code: "s7_cohabitant_etc", label: "동거인 기타", type: "text" },
      {
        code: "s7_children",
        label: "자녀",
        type: "select",
        group: "나. 수급자의 지지체계",
        options: ["없음", "있음"],
      },
      { code: "s7_children_sons", label: "아들 수", type: "number" },
      { code: "s7_children_daughters", label: "딸 수", type: "number" },
      { code: "s7_primary_caregiver", label: "주 수발자", type: "select", options: ["없음", "있음"] },
      {
        code: "s7_primary_caregiver_relation",
        label: "주 수발자의 관계",
        type: "select",
        options: ["배우자", "자녀", "며느리·사위", "형제·자매", "손자녀", "부모", "친척", "기타"],
      },
      {
        code: "s7_primary_caregiver_burden",
        label: "주 수발자의 부양부담",
        type: "select",
        options: ["전혀 부담되지 않음", "아주 가끔 부담됨", "가끔 부담됨", "자주 부담됨", "항상 부담됨"],
      },
      { code: "s7_alone_all_day", label: "하루종일 혼자있음", type: "select", options: ["예", "아니오"] },
      {
        code: "s7_family_contact",
        label: "가족 교류",
        type: "select",
        options: ["주 1~2회", "월 1~2회", "분기 1~2회", "연 1~2회", "없음"],
      },
      {
        code: "s7_friend_contact",
        label: "친구·이웃 교류",
        type: "select",
        options: ["주 1~2회", "월 1~2회", "분기 1~2회", "연 1~2회", "없음"],
      },
      {
        code: "s7_community_resources",
        label: "현재 이용 중인 지역사회 자원",
        type: "multiselect",
        group: "다. 지역사회 자원",
        options: [
          "없음",
          "노인맞춤돌봄서비스",
          "노인복지관",
          "보건의료서비스(보건소,치매안심센터 등)",
          "식사지원(급식 및 도시락 배달 등)",
          "이동지원서비스(차량지원,무료택시 등)",
          "주거지원서비스(도배,장판,주택개조 등)",
          "이미용서비스",
          "장애인활동지원서비스",
          "종교단체지원",
          "기타",
        ],
      },
      { code: "s7_community_resources_detail", label: "지역사회 자원 상세 (서비스 내용 등)", type: "text" },
      { code: "s7_opinion", label: "의견 및 판단근거", type: "textarea", group: "라. 의견" },
    ],
  },
  {
    code: "s8",
    title: "8. 수급자가 거주하는 곳의 환경",
    note: "시설급여기관은 해당하지 않습니다.",
    fields: [
      {
        code: "s8_floor",
        label: "거주하는 곳의 층수",
        type: "select",
        group: "가. 층수",
        options: ["지층", "1층", "2층", "3층 이상"],
      },
      { code: "s8_elevator", label: "엘리베이터", type: "select", options: ["있음", "없음"], group: "나. 생활환경" },
      { code: "s8_stairs", label: "실내·외 계단", type: "select", options: ["있음", "없음"] },
      { code: "s8_threshold", label: "실내 장애물(문턱)", type: "select", options: ["있음", "없음"] },
      { code: "s8_floor_wall", label: "바닥·벽지", type: "select", options: ["양호", "불량"] },
      { code: "s8_hvac", label: "냉·난방 및 환기", type: "select", options: ["양호", "불량"] },
      { code: "s8_lighting", label: "조명", type: "select", options: ["양호", "불량"] },
      { code: "s8_kitchen", label: "주방 상태", type: "select", options: ["양호", "불량"] },
      { code: "s8_toilet_location", label: "화장실 위치", type: "select", options: ["실내", "실외"] },
      { code: "s8_western_toilet", label: "좌변기", type: "select", options: ["있음", "없음"] },
      { code: "s8_hot_water", label: "온수", type: "select", options: ["있음", "없음"] },
      { code: "s8_shower", label: "샤워기", type: "select", options: ["있음", "없음"] },
      { code: "s8_sink", label: "세면대", type: "select", options: ["있음", "없음"] },
      { code: "s8_opinion", label: "의견 및 판단근거", type: "textarea", group: "다. 의견" },
    ],
  },
  {
    code: "s9",
    title: "9. 수급자 및 보호자가 희망하는 서비스",
    fields: [
      {
        code: "s9_physical_support",
        label: "신체활동 지원",
        type: "multiselect",
        group: "가. 신체활동 지원",
        options: [
          "개인위생(세면)",
          "개인위생(구강청결)",
          "개인위생(몸단장)",
          "개인위생(머리감기)",
          "개인위생(옷갈아입기)",
          "몸씻기(목욕)",
          "체위변경하기",
          "식사하기(식사도움)",
          "이동도움(부축,휠체어 등)",
          "화장실이용하기(이동변기,기저귀교환 등)",
        ],
      },
      {
        code: "s9_daily_support",
        label: "일상생활 지원",
        type: "multiselect",
        group: "나. 일상생활 지원",
        options: ["식사준비 및 정리", "청소·주변정돈", "의복세탁 및 관리", "장보기", "복약도움", "외출동행", "기타"],
      },
      {
        code: "s9_outing_detail",
        label: "외출동행 상세",
        type: "multiselect",
        options: ["병원", "관공서", "산책", "기타"],
      },
      { code: "s9_daily_support_etc", label: "일상생활 지원 기타", type: "text" },
      {
        code: "s9_rehab",
        label: "기능회복훈련",
        type: "multiselect",
        group: "다. 기능회복훈련",
        options: ["신체기능훈련", "일상생활동작훈련", "인지기능향상훈련", "여가·정서프로그램", "물리치료", "작업치료", "기타"],
      },
      { code: "s9_rehab_etc", label: "기능회복훈련 기타", type: "text" },
      {
        code: "s9_cognitive_support",
        label: "인지관리 및 정서지원",
        type: "multiselect",
        group: "라. 인지관리 및 정서지원",
        options: ["인지관리지원", "정서지원", "기타"],
      },
      { code: "s9_cognitive_support_etc", label: "인지관리 및 정서지원 기타", type: "text" },
      {
        code: "s9_health_care",
        label: "건강 및 간호관리",
        type: "multiselect",
        group: "마. 건강 및 간호관리",
        options: ["건강관리(투약관리 및 기초건강관리 등)", "간호관리(욕창,통증,호흡기,구강간호 등)"],
      },
      {
        code: "s9_bath",
        label: "방문목욕",
        type: "select",
        group: "바. 방문목욕",
        options: ["차량을 이용한 방문목욕", "차량을 이용하지 않은 방문목욕", "없음"],
      },
      { code: "s9_equipment_wish", label: "복지용구 희망품목", type: "text", group: "사. 복지용구" },
      {
        code: "s9_other_resources",
        label: "장기요양급여 외 희망하는 지역사회 자원",
        type: "multiselect",
        group: "아. 지역사회 자원",
        options: [
          "없음",
          "보건의료서비스",
          "노인복지관",
          "이동지원서비스",
          "식사지원",
          "이미용서비스",
          "주거지원서비스",
          "종교단체지원",
          "기타",
        ],
      },
      { code: "s9_opinion", label: "의견 및 판단근거", type: "textarea", group: "자. 의견" },
    ],
  },
];
